# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ntoskrnl.exe.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ntoskrnl(object):
    def setupUi(self, ntoskrnl):
        ntoskrnl.setObjectName("ntoskrnl")
        ntoskrnl.resize(191, 81)
        font = QtGui.QFont()
        font.setFamily("Alef")
        ntoskrnl.setFont(font)
        ntoskrnl.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label = QtWidgets.QLabel(ntoskrnl)
        self.label.setGeometry(QtCore.QRect(0, 0, 191, 81))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(ntoskrnl)
        QtCore.QMetaObject.connectSlotsByName(ntoskrnl)

    def retranslateUi(self, ntoskrnl):
        _translate = QtCore.QCoreApplication.translate
        ntoskrnl.setWindowTitle(_translate("ntoskrnl", "ntoskrnl.exe"))
        self.label.setText(_translate("ntoskrnl", "KERNEL CORRUPTION\n"
"THANKS FOR PLAYING\n"
"THIS IS STILL THE FIRST VERSION!!!\nMORE COMING SOON!!!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ntoskrnl = QtWidgets.QDialog()
    ui = Ui_ntoskrnl()
    ui.setupUi(ntoskrnl)
    ntoskrnl.show()
    sys.exit(app.exec_())
